[phases.setup]
nixPkgs = ["nodejs_18", "npm"]

[phases.install]
cmds = ["cd backend && PUPPETEER_SKIP_DOWNLOAD=true npm install --production --no-optional --ignore-scripts"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npm start"