# Railway Configuration for Location Intelligence Backend

[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

# Environment variables
[env]
NODE_ENV = "production"
PORT = "3001"

# Service configuration
[[services]]
name = "backend"
source = "."